version: '3.8'

services:
  app:
    image: todo-backend
    build:
      context: .  #will pick this dir as the build context
      dockerfile: dev.dockerfile  #which dockerfile to read
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    container_name: todo-frontend-con