version: '3.8'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mongo_data:/data/db
  redis:
    image: redis
    command: ['redis-server', '--appendonly', 'yes'] #overwrite the CMD
    volumes:
      - ./redis_data:/data
  server:
    image: todo-backend-con
    depends_on: 
      - mongo
      - redis
    build:
      context: .
      dockerfile: dev.Dockerfile  #use dev.Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules/  #not needed?
    environment:
      - REDIS_URL=redis://redis:6379  #changed localhost to redis
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database  #changed localhost to mongo
    ports:
      - 3001:3001
    container_name: todo-backend-con